services:
  ipbot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ipbot
    restart: always
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - TZ=UTC
